name: ana_mercado_mobile
description: A new Flutter project for Ana Mercado.
publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  fl_chart: ^0.65.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#2196F3" # MATCHING BLUE COLOR
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
